on:
  push:
    branches:
      - "features/**"
    paths:
      - "gateway-svc/**"
  pull_request:
    branches:
      - "features/**"
      - "fix/**"
    paths:
      - "gateway-svc/**"
jobs:
  push:
    name: gateway-svc-push
    if: github.event_name == 'push'
    uses: ./.github/workflows/ci-push-workflow-call.yaml
    with:
      SERVICE_NAME: gateway-svc
      SERVICE_PORT: 8000
    secrets: inherit

  pr:
    name: gateway-svc-pr
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/ci-pr-workflow-call.yaml
    with:
      SERVICE_NAME: gateway-svc
      SERVICE_PORT: 8000
    secrets: inherit